config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top", as: "top"
  get "homes/about" => "homes#about", as: "about"
  resources :books, only: [:index, :create, :show, :edit] 
  resources :users, only: [:top, :index, :show, :edit]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    top_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to books_path
  end
    

  def show
  end

  def edit
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
    
  end
  
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @user = current_user
    @users = User.all
  end

  def show
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path  
  end
  
    private

  def user_params
    params.require(:user).permit(:name, :book)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<h1>New book</h1>
<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Opinion</h4>
  <%= f.text_area :body %>
	
  <%= f.submit 'Creat Book' %>
<% end %>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/homes/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>bookers</title>
  </head>

  <body>
    <header>

    </header>
  </body>

  <main>
    <h1>welcome to Bookers !!</h1>
  </main>


  <footer>
    <p>CopyRight Infratop.inc</p>
  </footer>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
  </head>

  <body>
    <header></header>

    <main>
      <h1>welcome to Bookers !!</h1>
      <p>In Bookers,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <li>
        <%= link_to "Log in", new_user_session_path %>
      </li>
      <li>
        <%= link_to "Sign up", new_user_registration_path %>
      </li>
    </main>
  </body>

  <footer>
    <p>CopyRight Infratop.inc</p>
  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/ef37b76ac6.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <li>
          <%= link_to "Bookers", top_path %>
        </li>
        <li>
          <%= link_to "Home", top_path %>
        </li>
        <li>
          <%= link_to "Users", users_path %>
        </li>
        <li>
          <%= link_to "Books", books_path %>
        </li>
        <li>
          <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "Bookers", top_path %>
        </li>
        <li>
          <%= link_to "Home", top_path %>
        </li>
        <li>
          <%= link_to "About", about_path %>
        </li>
        <li>
          <%= link_to "Sign up", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "Log in", new_user_session_path %>
        </li>
      <% end %>
    </header>
    <%= yield %>
  </body>

</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
  </head>

  <body>
    <header></header>

    <main>
      <h2>User info</h2>
      
      
      <li>
        <%= link_to "Edit", edit_user_path %>
      </li>
  
  
      <h2>New book</h2>
        <%= form_with model: @book do |f| %>
      <h4>Title</h4>
        <%= f.text_field :title %>
      <h4>Opinion</h4>
        <%= f.text_area :body %>
      <li>
        <%= f.submit 'Creat Book' %>
      </li>
        <% end %>
    </main>
  </body>

  <footer>
    <p>CopyRight Infratop.inc</p>
  </footer>